version: '3'

services:

  app:
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: app
    volumes:
      - ./report:/srv/report
    depends_on:
      - db

  db:
    image: 'postgres:13-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: irbis
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"