spring:
  config:
    import: secrets.yml
  datasource:
#    url: jdbc:postgresql://localhost:5432/irbis
    url: jdbc:postgresql://db:5432/irbis
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
#    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: public

report:
  directory: "report/"
  prepend-timestamp: false

#  every day in 02 PM
  cron-expression: "0 2 * * * *"

#  every ten seconds
#  cron-expression: "*/10 * * * * *"

logging:
  level:
    org.springframework: info

springdoc:
  swagger-ui:
    path: /swagger-ui

