spring:
  config:
    import: secrets.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/irbis
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

report:
  directory: "report/"
  prepend-timestamp: false
#  cron-expression: "0 2 * * * *"
  cron-expression: "*/10 * * * * *"

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
