spring:
  config:
    import: secrets.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/irbis
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: public

report:
  directory: "report/"
  prepend-timestamp: false
  cron-expression: "0 2 * * * *"
#  cron-expression: "*/10 * * * * *"

logging:
  level:
    org.springframework: trace

